config/routes.rb
Rails.application.routes.draw do
  get 'welcome', to: 'login#show', as: 'welcome'

  match 'sessions/create', to: 'sessions#create', via: :post, as: 'login'
  match 'sessions/destroy', to: 'sessions#destroy', via: [:delete, :get], as: 'logout'

  # users shouldn't be accessible
  # get 'users', to: 'users#index', as: 'users'

  get 'users/new', to: 'users#new', as: 'register'
  post 'users', to: 'users#create', as: 'user'

  get 'users/:id/clear', to: 'users#clear_notifs' , as: 'clear_notifs'
  get 'users/:id/edit', to: 'users#edit' , as: 'edit_profile'
  put 'users/:id', to: 'users#update', as: 'update_profile'

  get 'users/forgotten'
  post 'users/send_forgotten'

  get 'users/:id', to: 'users#show', as: 'profile'

  delete 'users/:id/destroy', to: 'users#destroy', as: 'delete_profile'

  post 'cocktails/:id/share', to: 'cocktails#share', as: 'share_cocktail'

  resources :cocktails

  post 'ingredients/:id/share', to: 'ingredients#share', as: 'share_ingredient'
  post 'ingredients/:id/have', to: 'ingredients#have', as: 'store'

  resources :ingredients

  root :to => redirect('/welcome')
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  belongs_to :owner, class_name: "User", foreign_key: :user_id
  has_and_belongs_to_many :users
  has_and_belongs_to_many :ingredients

  validates :name, {presence: true}
  validates :img, {presence: true}

  before_save :normalize_blank_values

  def normalize_blank_values
    attributes.each do |column, value|
      self[column].present? || self[column] = nil
    end
  end

  def missing?
    missing = 0
    self.ingredients.each do |ingr|
      unless ingr.have
        missing += 1
      end
    end
    missing
  end
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :check_auth
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  # GET /cocktails
  # GET /cocktails.json
  def index
    @cocktails = []
    @auth_user.cocktails.each do |ct|
      @cocktails << ct
    end
  end

  def share
    @to = User.find_by_name(params[:username_to])

    if @to == nil
      render json: {'error': params[:username_to].to_s + " doesn't exist."}, status: 400
      return
    end

    find = @to.cocktails.select {|ct| ct.id == Integer(params[:id])}

    if find.empty?
      @ct = Cocktail.find_by_id(params[:id])
      @to.cocktails << @ct

      @notif = Notification.new(sender: @auth_user.id, item: @ct.id, item_type: 0, seen: false)
      @to.notifications << @notif

      render :json => @ct
    else
      render json: {'error': params[:username_to].to_s + " already have this cocktail."}, status: 400
    end
  end

  # GET /cocktails/1
  # GET /cocktails/1.json
  def show
    if @cocktail.users.select { |user| user == @auth_user }.empty?
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
    end
  end

  # GET /cocktails/new
  def new
    @cocktail = Cocktail.new(img: "/imgs/glass.jpg")
  end

  # GET /cocktails/1/edit
  def edit
  end

  # POST /cocktails
  # POST /cocktails.json
  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.owner = @auth_user

    respond_to do |format|
      if @cocktail.save
        if (params['cocktail']['ingredients'] != nil)
          for id in params['cocktail']['ingredients']
            @cocktail.ingredients << Ingredient.find(id)
          end
        end
        @auth_user.cocktails << @cocktail
        format.html {redirect_to cocktails_path, notice: 'Cocktail was successfully updated.'}
      else
        format.html {render :new}
        format.json {render json: @cocktail.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /cocktails/1
  # PATCH/PUT /cocktails/1.json
  def update
    respond_to do |format|
      if @cocktail.update(cocktail_params)
        if (params['cocktail']['ingredients'] != nil)
          for id in params['cocktail']['ingredients']
            @cocktail.ingredients << Ingredient.find(id)
          end
        end
        format.html {redirect_to @cocktail, notice: 'Cocktail was successfully updated.'}
        format.json {render :show, status: :ok, location: @cocktail}
      else
        format.html {render :edit}
        format.json {render json: @cocktail.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /cocktails/1
  # DELETE /cocktails/1.json
  def destroy
    notifs = Notification.where(item_type: 0, item: @cocktail.id)
    unless notifs == nil
      notifs.each do |nt|
        nt.destroy
      end
    end

    @cocktail.destroy
    respond_to do |format|
      format.html {redirect_to cocktails_url, notice: 'Cocktail was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  def check_auth
    unless session[:user]
      redirect_to welcome_path
      return
    end
    @auth_user = User.find_by_id(session[:user])
    unless @auth_user
      redirect_to logout_path
    end
  end

  def set_cocktail
    @cocktail = Cocktail.find_by_id(params[:id])
    if @cocktail == nil
      render(:file => File.join(Rails.root, 'public/404.html'), :status => 404, :layout => false)
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cocktail_params
    params.require(:cocktail).permit(:name, :img, :description, :recipe, {ingredients: [:id]})
  end
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/views/cocktails/_cocktail.html.erb
<% content_for :head do %>
  <link rel="stylesheet" href="/assets/cocktail-partial.css.scss">
<% end %>
<a href="cocktails/<%= ct.id %>" class="list-group-item share ctp-a <%= ct.missing? > 0 ? 'missing' : nil %>">
  <img src="<%= ct.img %>" alt="<%= ct.name %>" class="ctp-img"/>
  <div class="list-group-item-heading ctp-name">
    <h4><%= ct.name %></h4>
    <% if ct.missing? > 0 %>
      <h6 class="ctp-missing">Missing: <%= ct.missing? %> </h6>
    <% end %>
  </div>
  <input type="button" value="SHARE" class="ctp-share"
         onclick="share_it(<%= ct.id %>, '<%= share_cocktail_path(ct.id) %>')">
</a>

app/views/cocktails/_form.html.erb
<%= form_with(model: cocktail, local: true) do |form| %>
  <% if cocktail.errors.any? %>
<!--    <div id="error_explanation">-->
<!--      <h2><%#= pluralize(cocktail.errors.count, "error") %> prohibited this cocktail from being saved:</h2>-->

<!--      <ul>-->
        <%# cocktail.errors.full_messages.each do |message| %>
<!--          <li><%#= message %></li>-->
        <%# end %>
<!--      </ul>-->
<!--    </div>-->
  <% end %>

  <div class="ct-form cocktail">
    <img src="<%= @cocktail.img %>" alt="<%= @cocktail.name %>" class="ct-form img"/>
    <div class="ct-form ct-front">
      <%= form.text_area :name, class: 'ct-form line-textarea', placeholder: 'Name', rows: 1, cols: '50' %>
      <%= form.text_area :img, class: 'ct-form line-textarea', placeholder: 'Image URL e.g. /imgs/glass.png', rows: 1, cols: '50%' %>
    </div>
  </div>

  <div class="ct-form ct-desc">
    <h4>Description</h4>
    <%= form.text_area :description, class: 'ct-form big-textarea', rows: '5', cols: '100' %>
  </div>

  <div class="ct-form ct-recipe">
    <h4>Recipe</h4>
    <%= form.text_area :recipe, class: 'ct-form big-textarea', rows: '5', cols: '100' %>
  </div>


  <div class="ct-form ct-ingrs">
    <h4>Ingredients</h4>
    <div class="list-group">
      <% @auth_user.ingredients.each do |ingr| %>
        <%= render 'ingredients/ingr-select', ingr: ingr %>
      <% end %>
    </div>
  </div>

  <div class="ct-form btn-group btn-group-justified" role="group">
    <div class="btn-group" role="group">
      <button class="btn btn-info">Save</button>
    </div>
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-warning" OnClick="window.history.back()">Cancel</button>
    </div>
  </div>
<% end %>

app/views/cocktails/edit.html.erb
<%= render 'layouts/userbar', user: @auth_user %>

<div class="ct-edit cocktail">
  <div class="ct-edit header">Edit::<%= @cocktail.name %></div>

  <%= render 'form', cocktail: @cocktail %>
</div>

app/views/cocktails/index.html.erb
<% content_for :head do %>
  <script src="/js/share.js"></script>
<% end %>
<%= render 'layouts/userbar', user: @auth_user %>
<div class="ct-index page">
  <div id="cocktailList" class="tab-pane fade-in fade in active">
    <div class="list-group">
      <% @cocktails.each do |ct| %>
        <%= render 'cocktails/cocktail', ct: ct %>
      <% end %>

      <a href="/cocktails/new" class="list-group-item ct-index new">
        <img src="/imgs/plus.png" alt="plus" class="ct-index new-img"/>
      </a>
    </div>
  </div>
</div>
<script>
    $(".share").click(function (e) {
        if (e.target.tagName === "INPUT") {
            e.preventDefault();

            var btn = $("input[type='button'][name='" + e.target.name + "']");
            btn.click();
        }
    });
</script>

app/views/cocktails/new.html.erb
<%= render 'layouts/userbar', user: @auth_user %>

<div class="ct-new cocktail">
  <div class="ct-new header">NEW:Cocktail</div>

  <%= render 'form', cocktail: @cocktail %>
</div>

app/views/cocktails/show.html.erb
<% content_for :head do %>
  <script src="/js/share.js"></script>
<% end %>

<%= render 'layouts/userbar', user: @auth_user %>
<div class="ct-show page">
  <div class="ct-show header"></div>

  <div class="ct-show cocktail">
    <img src="<%= @cocktail.img %>" alt="<%= @cocktail.name %>" class="ct-show ct-img"/>
    <h4 class="list-group-item-heading ct-show ct-name"><%= @cocktail.name %></h4>
  </div>

  <div class="ct-show ct-desc">
    <h4>Description</h4>
    <p><%= @cocktail.description %></p>
  </div>

  <div class="ct-show ct-recipe">
    <h4>Recipe</h4>
    <p><%= @cocktail.recipe %></p>
  </div>

  <div class="ct-show ct-ingrs">
    <h4>Ingredients</h4>
    <div class="list-group">
      <% @cocktail.ingredients.each do |ingr| %>
        <%= render 'ingredients/ingredient', ingr: ingr %>
      <% end %>
    </div>
  </div>

  <div class="ct-show btn-group btn-group-justified" role="group">
    <div class="btn-group" role="group">
      <input type="button" value="Share" class="btn btn-primary" onclick="share_it(<%= @cocktail.id %>, '<%= share_cocktail_path(@cocktail.id) %>')">
    </div>
    <% if @cocktail.owner == @auth_user %>
      <div class="btn-group" role="group">
        <button class="btn btn-info" OnClick="location.href='/cocktails/<%= @cocktail.id %>/edit'">Edit</button>
      </div>
      <div class="btn-group" role="group">
        <%= link_to 'Delete', @cocktail, method: :delete, class: 'btn btn-danger', data: {confirm: 'Do you want to remove ' + @cocktail.name + '. This action can not be undone.'} %>
      </div>
    <% end %>
    <div class="btn-group" role="group">
      <button class="btn btn-warning" OnClick="location.href='/cocktails'">Back</button>
    </div>
  </div>
</div>