config/routes.rb
Rails.application.routes.draw do
  get 'welcome', to: 'login#show', as: 'welcome'

  match 'sessions/create', to: 'sessions#create', via: :post, as: 'login'
  match 'sessions/destroy', to: 'sessions#destroy', via: [:delete, :get], as: 'logout'

  # users shouldn't be accessible
  # get 'users', to: 'users#index', as: 'users'

  get 'users/new', to: 'users#new', as: 'register'
  post 'users', to: 'users#create', as: 'user'

  get 'users/:id/clear', to: 'users#clear_notifs' , as: 'clear_notifs'
  get 'users/:id/edit', to: 'users#edit' , as: 'edit_profile'
  put 'users/:id', to: 'users#update', as: 'update_profile'

  get 'users/forgotten'
  post 'users/send_forgotten'

  get 'users/:id', to: 'users#show', as: 'profile'

  delete 'users/:id/destroy', to: 'users#destroy', as: 'delete_profile'

  post 'cocktails/:id/share', to: 'cocktails#share', as: 'share_cocktail'

  resources :cocktails

  post 'ingredients/:id/share', to: 'ingredients#share', as: 'share_ingredient'
  post 'ingredients/:id/have', to: 'ingredients#have', as: 'store'

  resources :ingredients

  root :to => redirect('/welcome')
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :owner, class_name: "User", foreign_key: :user_id
  has_and_belongs_to_many :users
  has_and_belongs_to_many :cocktails

  validates :name, {presence: true}
  validates :img, {presence: true}

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :check_auth
  before_action :set_ingredient, only: [:show, :edit, :have, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = []
    @auth_user.ingredients.each do |ingr|
      @ingredients << ingr
    end
  end

  def share
    @to = User.find_by_name(params[:username_to])
    if @to == nil
      render json: {'error': params[:username_to].to_s + " doesn't exist."}, status: 400
      return
    end

    find = @to.ingredients.select {|ingr| ingr.id == Integer(params[:id])}

    if find.empty?
      @ingr = Ingredient.find_by_id(params[:id])
      @to.ingredients << @ingr

      @notif = Notification.new(sender: @auth_user.id, item: @ingr.id, item_type: 1, seen: false)
      @to.notifications << @notif

      render :json => @ingr
    else
      render json: {'error': params[:username_to].to_s + " already have this ingredient."}, status: 400
    end
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
    if @ingredient.users.select { |user| user == @auth_user }.empty?
      render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
    end
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new(img: "/imgs/ingredient.jpeg")
  end

  # GET /ingredients/1/edit
  def edit
  end

  def have
    @ingredient.have = params[:checked]
    unless Integer(params[:id]) < 0
      @ingredient.save
    end
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)
    @ingredient.owner = @auth_user

    respond_to do |format|
      if @ingredient.save
        @auth_user.ingredients << @ingredient

        format.html {redirect_to @ingredient, notice: 'Ingredient was successfully created.'}
        format.json {render :show, status: :created, location: @ingredient}
      else
        format.html {render :new}
        format.json {render json: @ingredient.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html {redirect_to @ingredient, notice: 'Ingredient was successfully updated.'}
        format.json {render :show, status: :ok, location: @ingredient}
      else
        format.html {render :edit}
        format.json {render json: @ingredient.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    notifs = Notification.where(item_type: 1, item: @ingredient.id)
    unless notifs == nil
      notifs.each do |nt|
        nt.destroy
      end
    end

    @ingredient.destroy
    respond_to do |format|
      format.html {redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  def check_auth
    unless session[:user]
      redirect_to welcome_path
      return
    end
    @auth_user = User.find_by_id(session[:user])
    unless @auth_user
      redirect_to logout_path
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_ingredient
    @ingredient = Ingredient.find_by_id(params[:id])
    if @ingredient == nil
      render(:file => File.join(Rails.root, 'public/404.html'), :status => 404, :layout => false)
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ingredient_params
    params.require(:ingredient).permit(:name, :img, :description, :have)
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient, local: true) do |form| %>
  <% if ingredient.errors.any? %>
<!--    <div id="error_explanation">-->
<!--      <h2><%#= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>-->

<!--      <ul>-->
        <%# ingredient.errors.full_messages.each do |message| %>
<!--          <li><%#= message %></li>-->
        <%# end %>
<!--      </ul>-->
<!--    </div>-->
  <% end %>

  <div class="ingr-form ingredient">
    <img src="<%= @ingredient.img %>" alt="<%= @ingredient.name %>" class="ingr-form img"/>
    <div class="ingr-form ingr-front">
      <%= form.text_area :name, class: 'ingr-form line-textarea', placeholder: 'Name', rows: 1, cols: '50'%>
      <%= form.text_area :img, class: 'ingr-form line-textarea', placeholder: 'Image URL e.g. /imgs/ingredient.jpeg', rows: 1, cols: '50%'%>
    </div>
  </div>

  <div class="ingr-form ingr-desc">
    <h4>Description</h4>
    <%= form.text_area :description, class: 'ct-form big-textarea', rows: '5', cols: '100'%>
  </div>

  <div class="ingr-form btn-group btn-group-justified" role="group">
    <div class="btn-group" role="group">
      <button class="btn btn-info">Save</button>
    </div>
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-warning" OnClick="window.history.back()">Cancel</button>
    </div>
  </div>
<% end %>

app/views/ingredients/_ingr-have.html.erb
<a href="/ingredients/<%= ingr.id %>" class="list-group-item share have ingr-a">
  <img src="<%= ingr.img %>" alt="<%= ingr.name %>" class="ingr-img"/>
  <h4 class="list-group-item-heading ingr-name"><%= ingr.name %></h4>
  <input type="checkbox" name="<%= ingr.id %>" class="ingr-chbox"
         <%= ingr.have ? 'checked' : nil %>
         onchange="check(this, '<%= ingr.id %>', '<%= store_path(ingr.id) %>')"/>
  <input type="button" value="SHARE" class="ingr-share"
         onclick="share_it(<%= ingr.id %>, '<%= share_ingredient_path(ingr.id) %>')">
</a>

app/views/ingredients/_ingr-select.html.erb
<% content_for :head do %>
  <link rel="stylesheet" href="/assets/ingredient-partial.css.scss">
<% end %>
<a class="list-group-item ingr-a">
  <img src="<%= ingr.img %>" alt="<%= ingr.name %>" class="ingr-img"/>
  <h4 class="list-group-item-heading ingr-name"><%= ingr.name %></h4>
  <input name="cocktail[ingredients][]" value=<%= ingr.id %> type="checkbox"
         <% $found = false %>
         <% @cocktail.ingredients.each do |ing| %>
         <% if ing.id == ingr.id
              $found = true
              break %>
         <% end %>
         <% end %>
         <%= $found ? 'checked' : nil %>
    class="ingr-chbox"/>
</a>

app/views/ingredients/_ingredient.html.erb
<% content_for :head do %>
  <link rel="stylesheet" href="/assets/igredient-partial.css.scss">
<% end %>
<a href="/ingredients/<%= ingr.id %>" class="list-group-item ingr-a">
  <img src="<%= ingr.img %>" alt="<%= ingr.name %>" class="ingr-img"/>
  <h4 class="list-group-item-heading ingr-name"><%= ingr.name %></h4>
</a>

app/views/ingredients/edit.html.erb
<%= render 'layouts/userbar', user: @auth_user %>

<div class="ingr-edit ingredient">
  <div class="ingr-edit header">Edit::<%= @ingredient.name %></div>

  <%= render 'form', ingredient: @ingredient %>
</div>

app/views/ingredients/index.html.erb
<% content_for :head do %>
  <script src="/js/share.js"></script>
<% end %>
<%= render 'layouts/userbar', user: @auth_user %>
<div class="ingr-index page">
  <div id="ingredientList" class="tab-pane fade-in fade in active">
    <div class="list-group">
      <% @ingredients.each do |ingr| %>
        <%= render 'ingredients/ingr-have', ingr: ingr %>
      <% end %>

      <a href="/ingredients/new" class="list-group-item ingr-index new">
        <img src="/imgs/plus.png" alt="plus" class="ingr-index new-img"/>
      </a>
    </div>
  </div>
</div>
<script>
    $(".have").click(function (e) {
        if (e.target.tagName === "INPUT") {
            e.preventDefault();

            var cbox = $("input[type='checkbox'][name='" + e.target.name + "']");
            cbox.prop('checked', cbox.checked);
            cbox.change();
        }
    });

    function check(cb, id, path) {
        $.ajax({
            type: 'POST',
            data: {
                authenticity_token: "<%= form_authenticity_token %>",
                id: id,
                checked: cb.checked
            },
            dataType: 'json',
            url: path,
            success: function (res) {
                cb.checked = !cb.checked;
            },
            error: function (xhr, ajaxOptions, thrownError) {
                console.log(xhr.status);
                console.log(thrownError);
            }
        });
    }
</script>

app/views/ingredients/new.html.erb
<%= render 'layouts/userbar', user: @auth_user %>

<div class="ingr-new ingredient">
  <div class="ingr-new header">New::Ingredient</div>

  <%= render 'form', ingredient: @ingredient %>
</div>

app/views/ingredients/show.html.erb
<% content_for :head do %>
  <script src="/js/share.js"></script>
<% end %>

<%= render 'layouts/userbar', user: @auth_user %>
<div class="ingr-show page">
  <div class="ingr-show header"></div>

  <div class="ingr-show ingredient">
    <img src="<%= @ingredient.img %>" alt="<%= @ingredient.img %>" class="ingr-show ingr-img"/>
    <h4 id="header4" class="list-group-item-heading ingr-show ingr-name"><%= @ingredient.name %></h4>
  </div>

  <div class="ingr-show ingr-desc">
    <h4>Description</h4>
    <p><%= @ingredient.description %></p>
  </div>

  <div class="ingr-show btn-group btn-group-justified" role="group">
    <div class="btn-group" role="group">
      <input type="button" value="Share" class="btn btn-primary" onclick="share_it(<%= @ingredient.id %>, '<%= share_ingredient_path(@ingredient.id) %>')">
    </div>
    <% if @ingredient.owner == @auth_user %>
      <div class="btn-group" role="group">
        <button class="btn btn-info" OnClick="location.href='/ingredients/<%= @ingredient.id %>/edit' ">Edit</button>
      </div>
      <div class="btn-group" role="group">
        <%= link_to 'Delete', @ingredient, method: :delete, class: 'btn btn-danger', style: 'color: white', data: {confirm: 'Do you want to remove ' + @ingredient.name + '. This action can not be undone.'} %>
      </div>
    <% end %>
    <div class="btn-group" role="group">
      <button class="btn btn-warning" OnClick="location.href='/ingredients'">Back</button>
    </div>
  </div>
</div>