config/routes.rb
Rails.application.routes.draw do
  get 'welcome', to: 'login#show', as: 'welcome'

  match 'sessions/create', to: 'sessions#create', via: :post, as: 'login'
  match 'sessions/destroy', to: 'sessions#destroy', via: [:delete, :get], as: 'logout'

  # users shouldn't be accessible
  # get 'users', to: 'users#index', as: 'users'

  get 'users/new', to: 'users#new', as: 'register'
  post 'users', to: 'users#create', as: 'user'

  get 'users/:id/clear', to: 'users#clear_notifs' , as: 'clear_notifs'
  get 'users/:id/edit', to: 'users#edit' , as: 'edit_profile'
  put 'users/:id', to: 'users#update', as: 'update_profile'

  get 'users/forgotten'
  post 'users/send_forgotten'

  get 'users/:id', to: 'users#show', as: 'profile'

  delete 'users/:id/destroy', to: 'users#destroy', as: 'delete_profile'

  post 'cocktails/:id/share', to: 'cocktails#share', as: 'share_cocktail'

  resources :cocktails

  post 'ingredients/:id/share', to: 'ingredients#share', as: 'share_ingredient'
  post 'ingredients/:id/have', to: 'ingredients#have', as: 'store'

  resources :ingredients

  root :to => redirect('/welcome')
end

app/views/layouts/_notif.html.erb
<% content_for :head do %>
  <link rel="stylesheet" href="/assets/notif.css.scss">
<% end %>
<% item = notif.get_item %>
<% sender = notif.get_sender %>
<a href="/<%= notif.type_string %>s/<%= notif.item %>" class="list-group-item nt-a">
  <img src="<%= item.img %>" alt="<%= item.name %>" class="nt-img"/>
  <div class="list-group-item-heading nt-name">
    <h4><b><%= sender.name %></b> shared a <%= notif.type_string %> named <b><%= item.name %></b> with you.</h4>
  </div>
</a>

app/views/layouts/_userbar.html.erb
<% content_for :head do %>
  <link rel="stylesheet" href="/assets/userbar.css.scss">
<% end %>
<div class="userbar user-bar">
  <div class="userbar logo-box">
    <div class="userbar dot">•</div>
    <img src="/imgs/logo-white.png" class="userbar logo-img">
  </div>

  <a href="<%= cocktails_path %>" class="userbar
    <%= current_page?(cocktails_path) ? 'page-selected' : 'page' %>">
    <div class="userbar profile-link">Cocktails</div>
  </a>
  <a href="<%= ingredients_path %>" class="userbar \
  <%= current_page?(ingredients_path) ? 'page-selected' : 'page' %>">
    <div class="userbar profile-link">Ingredients</div>
  </a>

  <a href="<%= logout_path %>" class="userbar profile-link">
    <div class="userbar logout">Logout</div>
  </a>
  <div class="userbar separator right">|</div>
  <a href="<%= profile_path(user) %>" class="userbar profile-link">
    <div class="userbar profile">
      <img src="<%= user.img %>" class="userbar profile-picture">
      <span class="userbar username"><%= user.name %></span>
      <div class="userbar notif-highlight <%= user.unseen_notifs > 0 ? 'notif-red' : nil %>">
        <%= user.unseen_notifs %>
        <img src="/imgs/bell.png" class="userbar notif-bell">
      </div>
    </div>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyVeryOwnBar</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <!-- Webfonts-->
  <link href="https://fonts.googleapis.com/css?family=Condiment:400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">

  <link rel="stylesheet" href="./css/bootstrap.min.css"/>
  <script src="./js/jquery.min.js"></script>
  <script src="./js/bootstrap.min.js"></script>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <% if content_for?(:head) %>
    <%= yield(:head) %>
  <% end %>
</head>

<body>
<%= yield %>
</body>
<footer>

</footer>
</html>